services:
  meupatrimonio-backend:
    build: ./backend
    container_name: meupatrimonio-backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/var/www
    networks:
      - meupatrimonio
  meupatrimonio-frontend:
    build: ./frontend
    container_name: meupatrimonio-frontend
    ports:
      - "5173:5173"
    networks:
      - meupatrimonio
  meupatrimonio-db:
    image: postgres:16
    container_name: meupatrimonio-db
    ports:
      - "5432:5432"
    env_file:
    - ./backend/.env
    environment:
      POSTGRES_DB: meupatrimonio
      POSTGRES_USER: meupatrimonio
      POSTGRES_PASSWORD: meupatrimonio
    networks:
      - meupatrimonio
networks:
  meupatrimonio:
    name: meupatrimonio
